#!/usr/bin/env python3
"""
Generate July 2026 content for ALL sections:
- Study: Ephesians series — "The Riches of Grace" (31 days)
- Family: "Building a Godly Home" (31 days)
- School: "Puritan Foundations" (31 days)
- Together: "Walking Together in Christ" (31 days)
- Proverb: Daily Proverbs July (31 days, theme: Wealth & Generosity)

Voice: en-GB-RyanNeural, rate=-6%, pitch=-3Hz, volume=+10%
"""

import asyncio, os, json, sys
from datetime import datetime

VOICE = "en-GB-RyanNeural"
RATE = "-6%"
PITCH = "-3Hz"
VOLUME = "+10%"
BASE_DIR = os.path.dirname(os.path.dirname(__file__))
AUDIO_DIR = os.path.join(BASE_DIR, "audio")
EPISODES_FILE = os.path.join(BASE_DIR, "episodes.json")
SCRIPTS_DIR = os.path.join(BASE_DIR, "scripts")

os.makedirs(SCRIPTS_DIR, exist_ok=True)

# ═══════════════════════════════════════════════════════════
# STUDY: Ephesians — "The Riches of Grace"
# 31 days through Ephesians with rich Puritan commentary
# ═══════════════════════════════════════════════════════════

STUDY_EPISODES = [
    # Ephesians 1
    {"day":1, "title":"Blessed with All Spiritual Blessings", "passage":"Ephesians 1:1-3",
     "text":"Paul, an apostle of Jesus Christ by the will of God, to the saints which are at Ephesus, and to the faithful in Christ Jesus: Grace be to you, and peace, from God our Father, and from the Lord Jesus Christ. Blessed be the God and Father of our Lord Jesus Christ, who hath blessed us with all spiritual blessings in heavenly places in Christ.",
     "exposition":"""Beloved, the apostle Paul opens this majestic epistle with a cascade of praise that ought to take our breath away. 'Blessed be the God and Father of our Lord Jesus Christ, who hath blessed us with all spiritual blessings in heavenly places in Christ.' Mark the comprehensiveness of this statement. Not some spiritual blessings, not many, but all. Every blessing that a soul can need for time and eternity has already been secured for us in Christ Jesus.

Thomas Goodwin, that prince among the Puritans, spent many years of his life expounding the riches of Ephesians, and he was fond of saying that this epistle is the Alps of the New Testament -- the very summit of divine revelation concerning the church and her blessings in Christ. And if that be so, then this opening doxology is the very peak of those Alps, from which we may survey the whole landscape of redeeming grace stretching out in every direction as far as the eye can see.

Consider the phrase 'in heavenly places in Christ.' Our blessings are not earthly and temporal, subject to the fluctuations of fortune and the ravages of time. They are heavenly -- secure, permanent, incorruptible. And they are in Christ -- not in ourselves, not in our works, not in our feelings, but in the unchangeable person and finished work of the Son of God. John Owen taught that the union of the believer with Christ is the foundation of all other blessings, for it is only as we are found in Him that every other gift of grace flows to us. The man who is in Christ lacks nothing. The man who is outside of Christ has nothing, though he possess the whole world.

Let us begin this month in Ephesians with hearts overflowing with gratitude, for the God who has blessed us is the God who planned our redemption before the foundation of the world. Every spiritual blessing we shall explore this month -- election, predestination, redemption, sealing, inheritance -- all of these are already ours, already secured, already accomplished in the eternal purpose of God. We do not hope for them as future possibilities; we receive them as present realities. Blessed be His glorious name forever. Amen."""},

    {"day":2, "title":"Chosen Before the Foundation of the World", "passage":"Ephesians 1:4-6",
     "text":"According as he hath chosen us in him before the foundation of the world, that we should be holy and without blame before him in love: having predestinated us unto the adoption of children by Jesus Christ to himself, according to the good pleasure of his will, to the praise of the glory of his grace, wherein he hath made us accepted in the beloved.",
     "exposition":"""Here is the fountain from which every stream of blessing flows: the eternal election of God. 'He hath chosen us in him before the foundation of the world.' Before the stars were flung into their courses, before the mountains were brought forth, before Adam drew his first breath in the Garden, God had already set His love upon His people and chosen them in Christ.

This doctrine of election has been the comfort and the strength of God's people in every age. The Puritans understood it as perhaps no other generation of Christians has understood it. William Perkins, that father of English Puritanism, taught that election is the golden chain that binds every link of salvation together, from foreknowledge to glorification. If God has chosen us, then nothing can separate us from His love. If He has predestinated us unto adoption, then no power in heaven or earth or hell can prevent us from reaching our Father's house.

But observe the purpose of election: 'that we should be holy and without blame before him in love.' God did not choose us because we were holy; He chose us that we might become holy. Election is not a license for carelessness but a call to consecration. As Thomas Watson memorably wrote, 'Election does not give us liberty to sin but to holiness.' The man who uses the doctrine of election as a pillow for sloth and sin has never truly understood it. For the purpose of God in choosing us was not merely to rescue us from hell, but to conform us to the image of His Son.

And the ultimate end of it all is this: 'to the praise of the glory of his grace.' We were chosen not for our glory, but for His. We were predestinated not to make much of ourselves, but to make much of God. The whole of salvation, from its eternal origin to its eternal consummation, is designed by infinite wisdom to display the exceeding riches of divine grace. And when we at last stand before the throne, the song upon our lips will not be 'worthy am I,' but 'worthy is the Lamb that was slain.' Amen."""},

    {"day":3, "title":"Redemption Through His Blood", "passage":"Ephesians 1:7-10",
     "text":"In whom we have redemption through his blood, the forgiveness of sins, according to the riches of his grace; wherein he hath abounded toward us in all wisdom and prudence; having made known unto us the mystery of his will, according to his good pleasure which he hath purposed in himself: that in the dispensation of the fulness of times he might gather together in one all things in Christ, both which are in heaven, and which are on earth; even in him.",
     "exposition":"""'In whom we have redemption through his blood.' These words take us from the councils of eternity to the cross of Calvary, from the decree of election to the execution of redemption. For what God purposed in eternity past, He accomplished in the fullness of time through the precious blood of His Son.

The word 'redemption' carries the idea of purchasing a slave out of the marketplace and setting him free. We were slaves to sin, in bondage to Satan, under the curse of the law, and utterly unable to deliver ourselves. But Christ entered the slave market of this fallen world, and with His own blood He paid the price of our freedom. Not with silver and gold, as Peter tells us, but with the precious blood of Christ, as of a lamb without blemish and without spot.

John Owen, in his monumental work 'The Death of Death in the Death of Christ,' argued that the blood of Christ was not merely sufficient for redemption but efficient -- that is, it actually accomplished what it was designed to accomplish. Christ did not merely make salvation possible; He actually saved His people. He did not simply open a door and hope that some would walk through it; He purchased, redeemed, and secured every soul that the Father had given Him.

And notice the measure of this grace: 'according to the riches of his grace.' Not merely according to the existence of His grace, as though God were a miser doling out the bare minimum. No! According to the riches -- the inexhaustible, immeasurable, unfathomable riches of divine grace. Jeremiah Burroughs taught that a man may give according to his riches without giving according to the riches of his riches. A wealthy man may give a penny -- that is according to his riches, in the sense that he has riches to give from. But God gives according to the riches of His grace, which means He gives lavishly, abundantly, overflowingly, as befits the infinite generosity of His nature.

Oh, what a gospel we have! Redemption full and free, forgiveness without measure, grace upon grace, all flowing to us through the blood of the eternal covenant. Let us never tire of proclaiming these unsearchable riches of Christ. Amen."""},

    {"day":4, "title":"Sealed with the Holy Spirit of Promise", "passage":"Ephesians 1:11-14",
     "text":"In whom also we have obtained an inheritance, being predestinated according to the purpose of him who worketh all things after the counsel of his own will: that we should be to the praise of his glory, who first trusted in Christ. In whom ye also trusted, after that ye heard the word of truth, the gospel of your salvation: in whom also after that ye believed, ye were sealed with that holy Spirit of promise, which is the earnest of our inheritance until the redemption of the purchased possession, unto the praise of his glory.",
     "exposition":"""The apostle now brings before us three glorious realities that belong to every true believer: an inheritance, a seal, and an earnest. Each one is a cause for unbounded joy and unshakeable confidence.

First, we have obtained an inheritance. The word in the original language may also be translated 'we were made God's inheritance.' This is a staggering thought -- not only do we inherit God's blessings, but God counts us as His inheritance, His treasured possession. As the Puritan Thomas Manton wrote, 'God's people are His portion, His jewels, His peculiar treasure. He values them above all the works of His hands.'

Second, we were sealed with the Holy Spirit of promise. In the ancient world, a seal served three purposes: it was a mark of ownership, a guarantee of authenticity, and a pledge of security. When God seals us with His Spirit, He marks us as His own, He authenticates our faith as genuine, and He guarantees that we shall be kept unto the day of final redemption. No forger can break this seal. No thief can steal what God has sealed. No power in the universe can unseal what the Almighty has closed.

Third, the Spirit is the earnest -- the down payment, the first installment -- of our inheritance. When you taste the joy of the Spirit in worship, that is a foretaste of heaven. When you feel the peace of God that passes understanding, that is an advance payment on the eternal rest. When you experience the love of God shed abroad in your heart, that is a sample of the ocean of love in which you shall swim forever.

Richard Sibbes, the heavenly doctor, used to say that the comforts of the Spirit in this life are but the bunch of grapes brought from Canaan -- enough to show us what the land is like, enough to make us long for the fullness that awaits us, but nothing compared to the abundance that shall be ours when we cross the Jordan and enter the promised land.

And once again, the grand purpose rings out: 'unto the praise of his glory.' This is the refrain of the whole chapter, the theme song of redemption. We were chosen for His glory. We were redeemed for His glory. We were sealed for His glory. And we shall be glorified -- for His glory. Amen."""},

    {"day":5, "title":"The Spirit of Wisdom and Revelation", "passage":"Ephesians 1:15-19",
     "text":"Wherefore I also, after I heard of your faith in the Lord Jesus, and love unto all the saints, cease not to give thanks for you, making mention of you in my prayers; that the God of our Lord Jesus Christ, the Father of glory, may give unto you the spirit of wisdom and revelation in the knowledge of him: the eyes of your understanding being enlightened; that ye may know what is the hope of his calling, and what the riches of the glory of his inheritance in the saints, and what is the exceeding greatness of his power to us-ward who believe.",
     "exposition":"""Having scaled the heights of doctrine in the first fourteen verses, Paul now falls upon his knees in prayer. And what a prayer it is! He does not pray for health, wealth, or earthly prosperity. He prays for something infinitely more valuable: spiritual illumination.

'That the God of our Lord Jesus Christ, the Father of glory, may give unto you the spirit of wisdom and revelation in the knowledge of him.' This is the great need of the church in every age -- not more information, but more illumination. We may have Bibles on our shelves and theology in our heads, yet remain blind to the glory of what we profess to believe. Jonathan Edwards understood this distinction better than most. He taught that there is a difference between having a rational understanding of divine truth and having a spiritual sense of its beauty and excellency. A man may understand the doctrine of God's grace the way he understands a mathematical theorem, without ever being ravished by its sweetness or humbled by its majesty.

Paul prays that three things in particular might be known: the hope of God's calling, the riches of His inheritance, and the exceeding greatness of His power. These three correspond roughly to our past, present, and future in Christ. The hope of His calling points to the certainty of our election and the glory for which we have been set apart. The riches of His inheritance points to the present reality of what we possess in Christ. And the exceeding greatness of His power points to the same resurrection force that raised Christ from the dead, which is at work in us even now.

John Flavel wrote that the power of God toward believers is the same power that conquered death, broke open the tomb, and seated Christ at the right hand of the Majesty on high. And if that power is for us, what can stand against us? If the arm that rolled away the stone from the sepulchre is the arm that upholds our faith, then our faith is as unshakeable as the throne of God itself.

May we never be content with a shallow, secondhand knowledge of God. May the Father of glory open our eyes to see what He has done, what He is doing, and what He shall yet do for those who love Him. Amen."""},

    {"day":6, "title":"Far Above All Principality and Power", "passage":"Ephesians 1:19-23",
     "text":"And what is the exceeding greatness of his power to us-ward who believe, according to the working of his mighty power, which he wrought in Christ, when he raised him from the dead, and set him at his own right hand in the heavenly places, far above all principality, and power, and might, and dominion, and every name that is named, not only in this world, but also in that which is to come: and hath put all things under his feet, and gave him to be the head over all things to the church, which is his body, the fulness of him that filleth all in all.",
     "exposition":"""The first chapter of Ephesians ends with one of the most exalted descriptions of Christ's glory in all of Scripture. Paul tells us that God raised Christ from the dead and seated Him at His right hand, far above all principality and power and might and dominion. This is not merely a statement about Christ's location; it is a declaration of His absolute and universal sovereignty.

Thomas Goodwin spent years meditating upon this passage, and he concluded that the exaltation of Christ is the pattern and guarantee of the exaltation of His people. Just as Christ was raised from the lowest depths to the highest heights, so His people shall be raised from the dust of death to the glory of heaven. And just as all things were put under Christ's feet, so all our enemies -- sin, death, Satan, the world -- are put under our feet in Him.

But the most astonishing statement in this passage is the last one: the church is Christ's body, 'the fulness of him that filleth all in all.' Think of it! Christ who fills all things is Himself filled by the church. The infinite God finds His completeness, as it were, in the company of redeemed sinners. Samuel Rutherford, that Scottish saint whose letters breathe the very air of heaven, once wrote that Christ considers Himself incomplete without His bride, just as a head is incomplete without a body. Not that Christ lacks anything in Himself, but that in His condescending love He has bound Himself to His people with bonds that cannot be broken.

What comfort this brings to the weakest and most trembling believer! You are a member of Christ's body. You are part of His fullness. He would no sooner cast you away than a man would amputate his own hand. You are joined to Him by the Spirit, united to Him by faith, and destined to share in His glory forever. As William Gurnall wrote in his great work 'The Christian in Complete Armour,' the believer's security rests not in his grip upon Christ, but in Christ's grip upon him. And the hand that holds you is the same hand that governs the universe. Amen."""},

    {"day":7, "title":"Dead in Trespasses and Sins", "passage":"Ephesians 2:1-3",
     "text":"And you hath he quickened, who were dead in trespasses and sins; wherein in time past ye walked according to the course of this world, according to the prince of the power of the air, the spirit that now worketh in the children of disobedience: among whom also we all had our conversation in times past in the lusts of our flesh, fulfilling the desires of the flesh and of the mind; and were by nature the children of wrath, even as others.",
     "exposition":"""After the glorious heights of chapter one, Paul now takes us into the depths -- the dark valley of our natural condition apart from grace. 'You were dead in trespasses and sins.' Not sick, not weak, not struggling -- dead. This is the Bible's diagnosis of the human condition, and it is the foundation upon which all true theology must be built.

The Puritans understood the doctrine of total depravity with a clarity and seriousness that is largely lost in our superficial age. They did not mean that every person is as bad as they could possibly be, but that every part of every person -- mind, will, affections, conscience -- is corrupted by sin and unable to contribute anything toward salvation. As Thomas Boston wrote in his masterwork 'Human Nature in Its Fourfold State,' man in his natural condition is not merely at a disadvantage; he is utterly helpless, as incapable of spiritual life as a corpse in a coffin is incapable of rising and walking.

Paul identifies three masters that governed our lives before grace: the world, the devil, and the flesh. We walked according to the course of this world -- following its fashions, imbibing its values, pursuing its pleasures. We were under the influence of the prince of the power of the air -- Satan himself, that ancient serpent who blinds the minds of the unbelieving and leads them captive at his will. And we were slaves to the lusts of our flesh -- not merely outward sins of the body, but inward corruptions of the mind.

And the verdict? 'Children of wrath, even as others.' By nature, not merely by practice, we were objects of God's just displeasure. We did not become children of wrath by sinning; we sinned because we were children of wrath. The corruption was in the root before it appeared in the fruit.

Why does Paul rehearse this dismal catalogue? Because we can never appreciate the height of grace until we understand the depth from which grace has lifted us. The man who thinks he was merely a little confused, a little mistaken, a little off course, will never marvel at his salvation. But the man who knows he was dead, enslaved, condemned -- that man will sing of grace forever. Amen."""},

    {"day":8, "title":"But God, Who Is Rich in Mercy", "passage":"Ephesians 2:4-7",
     "text":"But God, who is rich in mercy, for his great love wherewith he loved us, even when we were dead in sins, hath quickened us together with Christ, (by grace ye are saved;) and hath raised us up together, and made us sit together in heavenly places in Christ Jesus: that in the ages to come he might shew the exceeding riches of his grace in his kindness toward us through Christ Jesus.",
     "exposition":"""'But God.' These are perhaps the two greatest words in all the Bible. We were dead -- but God. We were enslaved -- but God. We were under wrath -- but God. The entire gospel is contained in this blessed conjunction. Our story was one of unrelieved darkness and despair, but God broke into the narrative with sovereign mercy and changed everything.

'Who is rich in mercy.' Not merely merciful, but rich in mercy -- overflowing, superabounding, inexhaustibly wealthy in compassion toward miserable sinners. John Bunyan, that immortal tinker of Bedford, knew something of this divine wealth. In his autobiography 'Grace Abounding to the Chief of Sinners,' he tells how he wrestled for years under the burden of his guilt, tormented by the fear that he had committed the unpardonable sin. And then one day, as he was walking through the fields, these words from Ephesians broke in upon his soul like the dawn of a new creation: 'But God, who is rich in mercy, for his great love wherewith he loved us.' Bunyan said that he felt as though he had been lifted out of a dungeon and set upon a rock, and from that day forward the mercy of God was the foundation of all his hope.

Observe when God loved us: 'even when we were dead in sins.' Not when we cleaned ourselves up. Not when we turned over a new leaf. Not when we made ourselves presentable. God loved us at our worst, in the very depth of our corruption and rebellion. This is the wonder of divine love -- it is not attracted by beauty in its object, but creates beauty where there was none. As Augustine famously said, 'God does not love us because we are valuable; we are valuable because God loves us.'

And what has this rich mercy accomplished? Three things, each more glorious than the last. He quickened us -- gave us new life when we were spiritually dead. He raised us up -- lifted us from the grave of sin to walk in newness of life. And He made us sit in heavenly places in Christ -- even now, in our present experience, we are seated with Christ in the realm of spiritual authority and blessing. The same three steps that marked Christ's exaltation -- resurrection, ascension, enthronement -- are applied to every believer.

And all of this for one grand purpose: 'that in the ages to come he might shew the exceeding riches of his grace.' Throughout all eternity, redeemed sinners will be the exhibition, the demonstration, the proof of what divine grace can do. Angels will look upon us and marvel. The principalities and powers will behold us and worship. And we ourselves shall stand in the light of God's glory, trophies of His mercy forever. Amen."""},

    {"day":9, "title":"By Grace Through Faith", "passage":"Ephesians 2:8-10",
     "text":"For by grace are ye saved through faith; and that not of yourselves: it is the gift of God: not of works, lest any man should boast. For we are his workmanship, created in Christ Jesus unto good works, which God hath before ordained that we should walk in them.",
     "exposition":"""Here is the clearest, most concise statement of the Protestant gospel in all of Scripture. Three verses that shook the world when Martin Luther and the Reformers rediscovered them, and that continue to liberate captive souls to this day.

'By grace are ye saved through faith.' Grace is the source; faith is the instrument. Grace is the ocean; faith is the cup that drinks from it. Grace is God's part; faith is our response -- but even that response, Paul hastens to add, is 'not of yourselves: it is the gift of God.' The whole of salvation, from first to last, is a gift. The plan is a gift. The execution is a gift. The application is a gift. Even the hand that receives the gift is itself a gift.

The Puritans labored with great care to maintain the proper relationship between grace and works. They were fierce opponents of both legalism and antinomianism -- both the error that says works contribute to salvation and the error that says salvation has nothing to do with works. Listen to how Paul holds both truths together with perfect balance: 'Not of works, lest any man should boast. For we are his workmanship, created in Christ Jesus unto good works.' We are not saved by good works, but we are saved unto good works. Good works are not the root of salvation but the fruit of salvation. They do not earn our acceptance with God, but they demonstrate it.

Richard Baxter, though sometimes suspected of leaning too far toward the importance of works, actually expressed this truth with great beauty when he wrote, 'Good works are not the way to heaven, but they are the way of heaven. They are not the cause of our salvation, but they are the evidence of it. They do not purchase our inheritance, but they show that we are heirs.'

And then comes that magnificent word: 'workmanship.' In the original Greek, the word is poiema, from which we get our English word 'poem.' We are God's poem, His masterpiece, His work of art. Every believer is a new creation, shaped by the hands of the divine Artist to display the beauty of His grace. And the good works that flow from our new nature are not random or accidental; they were 'before ordained' -- planned in advance by God Himself. The same God who planned your salvation before the foundation of the world also planned the good works you would do after your salvation. Nothing is left to chance. Everything is by design. And the Designer is infinitely wise, infinitely good, and infinitely gracious. Amen."""},

    {"day":10, "title":"Made Nigh by the Blood of Christ", "passage":"Ephesians 2:11-16",
     "text":"Wherefore remember, that ye being in time past Gentiles in the flesh, who are called Uncircumcision by that which is called the Circumcision in the flesh made by hands; that at that time ye were without Christ, being aliens from the commonwealth of Israel, and strangers from the covenants of promise, having no hope, and without God in the world: but now in Christ Jesus ye who sometimes were far off are made nigh by the blood of Christ. For he is our peace, who hath made both one, and hath broken down the middle wall of partition between us.",
     "exposition":"""Paul now turns from the individual experience of salvation to its corporate dimensions. The Gentiles who were once strangers and aliens, far off from God and His covenant people, have been brought near by the blood of Christ. And not only brought near, but united with Jewish believers into one new body, one new humanity, one new temple.

'He is our peace.' Not merely that He gives peace or teaches peace, but that He Himself is our peace. In His own body on the cross, He broke down the wall of hostility that separated Jew from Gentile, and created in Himself one new man in place of the two. The ceremonial law with its regulations and ordinances, which had served as a dividing wall, was abolished -- not because it was evil, but because it had served its purpose as a guardian until Christ came.

Samuel Bolton, in his excellent treatise 'The True Bounds of Christian Freedom,' taught that Christ fulfilled the law in every respect -- its moral demands by His perfect obedience, its ceremonial shadows by His substance, and its penal curse by His suffering. Therefore the believer, whether Jew or Gentile, stands before God not on the ground of legal obedience but on the ground of Christ's finished work. The middle wall is down. The distinction is abolished. There is neither Jew nor Greek in Christ Jesus.

What a powerful word this is for our divided age! The gospel does not merely tolerate diversity; it creates unity out of the deepest divisions. If the blood of Christ could reconcile Jew and Gentile -- two peoples separated by centuries of hatred, by divine law, by cultural incompatibility -- then there is no human division that the cross cannot heal. The gospel is the only true foundation for unity, because it brings every soul to the same level at the foot of the cross, where all are equally sinful, equally helpless, and equally loved. Amen."""},
]

# Days 11-31: continue through Ephesians 2-6
STUDY_EPISODES += [
    {"day":11, "title":"Built Upon the Foundation of the Apostles", "passage":"Ephesians 2:17-22",
     "text":"And came and preached peace to you which were afar off, and to them that were nigh. For through him we both have access by one Spirit unto the Father. Now therefore ye are no more strangers and foreigners, but fellowcitizens with the saints, and of the household of God; and are built upon the foundation of the apostles and prophets, Jesus Christ himself being the chief corner stone.",
     "exposition":"Paul now reveals the glorious architecture of the church. We are no longer strangers but fellow citizens, no longer foreigners but members of God's household. And this household is built upon the foundation of the apostles and prophets, with Jesus Christ Himself as the chief cornerstone. Every stone in this spiritual temple is a living soul, placed by the hand of God in precisely the right position. As William Perkins taught, the church is not a human institution but a divine construction, and its builder and maker is God. The cornerstone determines the alignment of every other stone. Christ sets the standard, the direction, and the character of the whole building. Remove the cornerstone, and the entire structure collapses. But as long as Christ remains, the building stands secure against every storm of persecution, every flood of heresy, and every earthquake of cultural change. And we are being built together -- not as isolated stones piled in a heap, but as a coordinated structure, each stone bearing weight, each stone supporting its neighbor, each stone contributing to the beauty and strength of the whole. This is the church of the living God, and the gates of hell shall not prevail against it. Amen."},
    {"day":12, "title":"The Mystery of Christ Revealed", "passage":"Ephesians 3:1-7",
     "text":"For this cause I Paul, the prisoner of Jesus Christ for you Gentiles, if ye have heard of the dispensation of the grace of God which is given me to you-ward: how that by revelation he made known unto me the mystery; as I wrote afore in few words.",
     "exposition":"Paul calls himself 'the prisoner of Jesus Christ,' not the prisoner of Rome. Though chains bound his wrists, his spirit was free, for he understood that even his imprisonment was part of God's sovereign plan for the spread of the gospel. The mystery he speaks of is that Gentiles are fellow heirs with Israel, members of the same body, sharers in the same promise. This was hidden in ages past but now revealed by the Spirit. John Owen observed that God's method of revelation is progressive -- He unfolds His purposes gradually, like the dawn that grows brighter and brighter unto the perfect day. The inclusion of the Gentiles was always in the plan, foreshadowed in Abraham's call to be a blessing to all nations, but it was not fully understood until the Spirit illuminated the apostles. What a wonder that God would use a former persecutor of the church as the chief apostle to the nations! This is grace upon grace -- not only saving Paul from his sins but commissioning him to proclaim the very gospel he once sought to destroy. As Augustine said, 'God does not merely forgive the sinner; He transforms him into a saint and then makes him an apostle.' Amen."},
    {"day":13, "title":"The Unsearchable Riches of Christ", "passage":"Ephesians 3:8-13",
     "text":"Unto me, who am less than the least of all saints, is this grace given, that I should preach among the Gentiles the unsearchable riches of Christ.",
     "exposition":"'Unsearchable riches' -- what a phrase! The Greek word means 'untraceable,' like a path through a forest so vast that no one can map its boundaries. The riches of Christ are inexhaustible. You may spend an eternity exploring them and never reach the end. Thomas Goodwin said that heaven itself will be an eternal unfolding of the riches of Christ, and that after ten thousand years of discovery, we shall feel as though we have only just begun. Paul counts himself 'less than the least of all saints' -- a remarkable expression that shows how deeply the memory of his former persecution of the church had humbled him. True greatness in the kingdom of God is always accompanied by deep humility. The man who has seen most of God's glory is the man who is most conscious of his own unworthiness. Spurgeon once said, 'The more a man grows in grace, the less he thinks of himself.' This is not false modesty or self-deprecation; it is the natural response of a soul that has been overwhelmed by the grace of God. When you stand at the foot of a mountain, you feel your own smallness. When you stand at the foot of Calvary, you feel it infinitely more. Amen."},
    {"day":14, "title":"Strengthened with Might in the Inner Man", "passage":"Ephesians 3:14-19",
     "text":"For this cause I bow my knees unto the Father of our Lord Jesus Christ, of whom the whole family in heaven and earth is named, that he would grant you, according to the riches of his glory, to be strengthened with might by his Spirit in the inner man; that Christ may dwell in your hearts by faith; that ye, being rooted and grounded in love, may be able to comprehend with all saints what is the breadth, and length, and depth, and height; and to know the love of Christ, which passeth knowledge, that ye might be filled with all the fulness of God.",
     "exposition":"Here is the second great prayer of Ephesians, and it is even more staggering than the first. Paul prays that we might know the love of Christ 'which passeth knowledge' -- a love so vast that it surpasses the capacity of the human mind to comprehend it. It has breadth enough to encompass all nations and peoples. It has length enough to stretch from eternity past to eternity future. It has depth enough to reach the lowest sinner in the deepest pit. It has height enough to raise that sinner to the throne of God. Samuel Rutherford, writing from his exile in Aberdeen, poured out his heart in language that burns with holy passion: 'O love of Christ! O exceeding, boundless love! I cannot reach it, I cannot fathom it, I am swallowed up in its immensity.' The ultimate purpose of this prayer is breathtaking: 'that ye might be filled with all the fulness of God.' Not merely touched by God, not merely influenced by God, but filled with all the fullness of the infinite, eternal God. This is our destiny, beloved. This is what we were made for. And the Spirit of God is working in us even now to bring it to pass. Amen."},
    {"day":15, "title":"Exceeding Abundantly Above All We Ask", "passage":"Ephesians 3:20-21",
     "text":"Now unto him that is able to do exceeding abundantly above all that we ask or think, according to the power that worketh in us, unto him be glory in the church by Christ Jesus throughout all ages, world without end. Amen.",
     "exposition":"Paul concludes the doctrinal portion of Ephesians with this magnificent doxology. God is able to do what we ask. He is able to do above what we ask. He is able to do abundantly above what we ask. He is able to do exceeding abundantly above all that we ask or think. Each word piles upon the last, as if Paul cannot find language adequate to express the limitless capacity of God's power and generosity. As the Puritan Thomas Manton wrote, 'Prayer is the measure of our desires, but God's giving exceeds even the measure of our prayers.' We ask for a drop, and He gives an ocean. We ask for a crumb, and He spreads a feast. We ask for strength to endure, and He gives power to triumph. The key to unlocking this power is found in those words 'according to the power that worketh in us.' The same Holy Spirit who raised Christ from the dead is the power at work within every believer. We are not drawing upon an external resource; we carry within us the very power of God. And this power is not a static deposit but a living, active, working force that transforms us from glory to glory. May we never limit God by the smallness of our prayers. May we dare to ask great things, expect great things, and give Him glory when He does exceeding abundantly above all that we ask or think. Amen."},
    {"day":16, "title":"Walk Worthy of the Calling", "passage":"Ephesians 4:1-6",
     "text":"I therefore, the prisoner of the Lord, beseech you that ye walk worthy of the vocation wherewith ye are called, with all lowliness and meekness, with longsuffering, forbearing one another in love; endeavouring to keep the unity of the Spirit in the bond of peace.",
     "exposition":"With chapter four, Paul transitions from doctrine to duty, from creed to conduct, from what God has done to how we should live. The word 'therefore' is the hinge upon which the whole epistle turns. Because God has blessed us, chosen us, redeemed us, quickened us, seated us in heavenly places -- therefore, we must walk worthy of so great a salvation. The Puritans were masters at connecting doctrine to practice. They never taught truth in the abstract; they always pressed it home to the conscience and the daily life. As John Owen said, 'A man may have his head full of truth and his heart empty of grace.' The test of true theology is not how much we know but how we live. And the first virtue Paul commends is lowliness -- humility. Not the groveling false humility that says 'I am nothing,' but the settled, sober self-assessment that comes from knowing God's greatness and our dependence upon Him. From humility flows meekness, patience, forbearance, and love -- the virtues that preserve the unity of the Spirit. Unity is not something we create; it is something the Spirit has already created, and our task is to keep it, to guard it, to protect it from the divisive forces of pride, jealousy, and selfish ambition. Amen."},
    {"day":17, "title":"Gifts for the Building Up of the Body", "passage":"Ephesians 4:7-16",
     "text":"But unto every one of us is given grace according to the measure of the gift of Christ. And he gave some, apostles; and some, prophets; and some, evangelists; and some, pastors and teachers; for the perfecting of the saints, for the work of the ministry, for the edifying of the body of Christ.",
     "exposition":"Christ ascended to heaven not to leave His church helpless, but to equip her with everything she needs. He gave gifts -- not primarily miraculous gifts for individual display, but ministry gifts for corporate edification. Apostles, prophets, evangelists, pastors and teachers -- these are Christ's gift to His church, given for the perfecting of the saints and the building up of the body. Richard Baxter, in his 'Reformed Pastor,' wrote with passionate urgency about the responsibility of those called to shepherd God's flock. The purpose of all ministry, Paul says, is to bring every believer to maturity -- to the measure of the stature of the fullness of Christ. We are not to remain spiritual infants, tossed about by every wind of doctrine. We are to grow up in all things into Christ, who is the head. And this growth happens not in isolation but in community -- each joint supplying, each part working, each member contributing to the health and growth of the whole body. The individualism of our age is foreign to the New Testament. God has designed us to need one another, and the body of Christ functions properly only when every member fulfills its God-given role. Amen."},
    {"day":18, "title":"Put Off the Old Man, Put On the New", "passage":"Ephesians 4:17-24",
     "text":"This I say therefore, and testify in the Lord, that ye henceforth walk not as other Gentiles walk, in the vanity of their mind, having the understanding darkened, being alienated from the life of God through the ignorance that is in them, because of the blindness of their heart.",
     "exposition":"The Christian life is a daily exchange -- putting off the old man with his corrupt practices and putting on the new man, created in righteousness and true holiness. This is not a once-for-all transaction but a continual discipline, a lifelong battle against the remaining corruption in our nature. John Owen, in his masterful work 'The Mortification of Sin,' taught that the old nature does not die quietly. It fights, it schemes, it disguises itself, and the moment we relax our vigilance, it surges back with terrible force. But we do not fight alone. The Spirit who regenerated us is the Spirit who sanctifies us, and His power is infinitely greater than the power of sin. Thomas Brooks, in his 'Precious Remedies Against Satan's Devices,' catalogued dozens of strategies the enemy uses to draw believers back into the patterns of the old life. But against every device of Satan, there is a remedy in Christ. Against every temptation, there is a promise. Against every weakness, there is grace sufficient. The key is to be renewed in the spirit of our mind -- to think differently, to see the world through the lens of Scripture, to evaluate everything by the standard of Christ. As a man thinks in his heart, so is he. When our minds are renewed, our lives follow. Amen."},
    {"day":19, "title":"Grieve Not the Holy Spirit", "passage":"Ephesians 4:25-32",
     "text":"And grieve not the holy Spirit of God, whereby ye are sealed unto the day of redemption. Let all bitterness, and wrath, and anger, and clamour, and evil speaking, be put away from you, with all malice: and be ye kind one to another, tenderhearted, forgiving one another, even as God for Christ's sake hath forgiven you.",
     "exposition":"'Grieve not the Holy Spirit.' What a tender expression! The Spirit is not an impersonal force but a divine Person who can be grieved. And what grieves Him? Not primarily the great sins that shock the world, but the everyday sins of the tongue and the heart -- bitterness, wrath, anger, clamour, evil speaking, malice. These are the sins that poison relationships, divide churches, and quench the Spirit's work in our midst. Thomas Watson wrote, 'An unkind word from a believer's tongue does more damage to the cause of Christ than a thousand blasphemies from the world.' How sobering. The antidote is not merely restraint but transformation: be kind, tenderhearted, forgiving -- even as God for Christ's sake hath forgiven you. The measure of our forgiveness toward others is the measure of God's forgiveness toward us. If we truly grasp how much we have been forgiven, we will find it impossible to hold grudges against those who have wronged us. As the Puritan William Gurnall taught, 'He who has been forgiven a debt of ten thousand talents will not strangle his brother for a hundred pence.' Amen."},
    {"day":20, "title":"Walk in Love as Christ Loved Us", "passage":"Ephesians 5:1-7",
     "text":"Be ye therefore followers of God, as dear children; and walk in love, as Christ also hath loved us, and hath given himself for us an offering and a sacrifice to God for a sweetsmelling savour.",
     "exposition":"'Followers of God' -- the word is literally 'imitators.' We are to imitate God as children imitate a beloved father. And what is the chief attribute we are to imitate? Love. Not sentimental emotion, but the self-sacrificing love demonstrated at Calvary. Christ gave Himself for us. This is the pattern. This is the measure. This is the standard against which all our love must be tested. The Puritans understood that love without sacrifice is mere sentimentality, and sacrifice without love is mere duty. But love joined to sacrifice -- this is the very heartbeat of the gospel. Jonathan Edwards wrote that true virtue consists in benevolence toward being in general, but its purest expression is in love toward God and toward those whom God loves. Such love is costly. It demands the death of selfishness, the crucifixion of pride, the surrender of personal rights. But it is also glorious, for it reflects the very character of God Himself. When we walk in love, we walk in God's footsteps. When we give ourselves for others, we echo the gift of Christ. Amen."},
    {"day":21, "title":"Walk as Children of Light", "passage":"Ephesians 5:8-14",
     "text":"For ye were sometimes darkness, but now are ye light in the Lord: walk as children of light: for the fruit of the Spirit is in all goodness and righteousness and truth.",
     "exposition":"Note the radical language: Paul does not say we were in darkness but we were darkness itself. Our very nature was dark. But now, through the regenerating work of the Spirit, we are light in the Lord. This is not merely a change of position but a change of nature. As Thomas Goodwin observed, 'God does not merely move us from one room to another; He recreates us as entirely new beings.' And as children of light, we are to produce the fruit of light: goodness, righteousness, and truth. These are not decorations we add to our character; they are the natural produce of a nature that has been transformed by grace. The light reveals what darkness hides. The Christian life is a life of transparency, honesty, and openness before God and before men. We have nothing to hide, for our acceptance is not based on our performance but on the finished work of Christ. Walking in the light means living in reality -- facing the truth about ourselves, about God, and about the world. It means confessing our sins rather than concealing them. It means pursuing righteousness rather than rationalizing compromise. Awake, thou that sleepest, and arise from the dead, and Christ shall give thee light. Amen."},
    {"day":22, "title":"Be Filled with the Spirit", "passage":"Ephesians 5:15-21",
     "text":"And be not drunk with wine, wherein is excess; but be filled with the Spirit; speaking to yourselves in psalms and hymns and spiritual songs, singing and making melody in your heart to the Lord.",
     "exposition":"'Be filled with the Spirit.' This is not a suggestion but a command, and it is in the present tense, meaning we are to be continually, habitually filled. Just as a drunkard is controlled by wine, so the believer is to be controlled by the Spirit. But while wine leads to dissipation and ruin, the Spirit leads to worship, gratitude, and mutual submission. John Owen wrote three massive volumes on the work of the Holy Spirit, and his conclusion was this: the Spirit-filled life is not marked primarily by ecstatic experiences or miraculous gifts, but by the steady production of Christ-like character -- love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, and self-control. The evidence of being filled with the Spirit, Paul tells us, is corporate worship: speaking to one another in psalms and hymns, singing and making melody in the heart. A Spirit-filled church is a singing church, a thankful church, a submissive church. And the fountain from which all these virtues flow is a heart that is continually being renewed by the presence and power of the Holy Spirit. Amen."},
    {"day":23, "title":"Wives and Husbands, Christ and the Church", "passage":"Ephesians 5:22-33",
     "text":"Wives, submit yourselves unto your own husbands, as unto the Lord. Husbands, love your wives, even as Christ also loved the church, and gave himself for it.",
     "exposition":"Paul takes the most intimate of human relationships and sets it against the backdrop of the most glorious of divine realities: the love of Christ for His church. Marriage, he tells us, is not merely a social institution or a legal contract; it is a living picture of the gospel. The husband is called to love his wife as Christ loved the church -- which means laying down his life for her, nourishing her, cherishing her, seeking her highest good at the cost of his own comfort. As Matthew Henry beautifully wrote, 'The woman was not made out of man's head to rule over him, nor out of his feet to be trampled upon by him, but out of his side to be equal with him, under his arm to be protected, and near his heart to be loved.' The wife is called to submit as the church submits to Christ -- not as a slave to a tyrant, but as a beloved bride to a loving Savior who has given everything for her. Richard Baxter, in his 'Christian Directory,' counseled couples to see their marriage as a small church within the larger church, a place where the gospel is lived out daily in the thousand small acts of love, patience, forgiveness, and self-sacrifice that make up the fabric of married life. This is the great mystery, Paul says -- he is speaking of Christ and the church. Amen."},
    {"day":24, "title":"Children and Parents in the Lord", "passage":"Ephesians 6:1-4",
     "text":"Children, obey your parents in the Lord: for this is right. Honour thy father and mother; which is the first commandment with promise; that it may be well with thee, and thou mayest live long on the earth. And, ye fathers, provoke not your children to wrath: but bring them up in the nurture and admonition of the Lord.",
     "exposition":"The Christian household is a school of godliness, and the parent-child relationship is one of its primary classrooms. Children are commanded to obey -- not because parents are always right, but because this is the order God has established for the nurture and protection of those who are not yet mature enough to guide themselves. Cotton Mather, that prodigious Puritan of New England, wrote extensively on the duty of parents to catechize their children, to pray with them morning and evening, and to set before them by daily example what it means to follow Christ. He taught that the home is the first church, the first school, and the first government a child will ever know, and that the habits formed in childhood will shape the entire course of a person's life. But Paul also speaks to fathers: 'Provoke not your children to wrath.' This is a warning against harsh, unreasonable, arbitrary, or cruel discipline that crushes the spirit rather than shaping the character. As Jonathan Edwards practiced in his own home, the goal of Christian parenting is not mere obedience but the cultivation of genuine faith, love for God, and a heart that delights in righteousness. Bring them up in the nurture and admonition of the Lord -- with tenderness and instruction, with discipline and love, with firmness and grace. Amen."},
    {"day":25, "title":"The Whole Armour of God", "passage":"Ephesians 6:10-13",
     "text":"Finally, my brethren, be strong in the Lord, and in the power of his might. Put on the whole armour of God, that ye may be able to stand against the wiles of the devil. For we wrestle not against flesh and blood, but against principalities, against powers, against the rulers of the darkness of this world, against spiritual wickedness in high places.",
     "exposition":"Paul's final exhortation is a call to arms. The Christian life is not a leisurely stroll through a garden; it is a fierce battle against unseen enemies of terrifying power. William Gurnall's magisterial work 'The Christian in Complete Armour' runs to over a thousand pages of exposition on this single passage, and he confessed that even after years of study, he had barely scratched the surface. Our enemies are not human; they are spiritual forces of wickedness in the heavenly realms. We cannot see them, but they can see us. We cannot match them in our own strength, but we need not try, for the armor we wear is God's armor, forged in the furnace of divine omnipotence. 'Be strong in the Lord' -- not in yourself, not in your gifts, not in your experience, but in the Lord and in the power of His might. As Thomas Brooks taught, the soldier who goes into battle trusting in his own sword will be cut down in the first engagement. But the soldier who goes in trusting the Captain of his salvation will stand when the smoke clears. Put on the whole armor -- not part of it, not most of it, but every piece. For the enemy is cunning, and he will attack wherever he finds us unprotected. Amen."},
    {"day":26, "title":"The Belt of Truth and the Breastplate of Righteousness", "passage":"Ephesians 6:14",
     "text":"Stand therefore, having your loins girt about with truth, and having on the breastplate of righteousness.",
     "exposition":"The first piece of armor is truth. A Roman soldier's belt held everything together; without it, his tunic would flap loose and his sword would have nothing to hang from. So truth is the foundation of the Christian's defense. Truth about God, truth about ourselves, truth about sin and salvation, truth about the promises of Scripture. When Satan attacks, he begins with lies -- questioning God's word, distorting God's character, minimizing sin, exaggerating our failures. The man who is girded with truth can recognize and reject every lie. The breastplate of righteousness protects the heart -- and here it refers not only to the imputed righteousness of Christ that gives us our standing before God, but also the practical righteousness of daily obedience that gives us confidence in the heat of battle. As John Owen taught, the believer who tolerates known sin in his life has a gap in his armor that the enemy will exploit without mercy. Pursue holiness, for the breastplate of righteousness is your protection against the accusing darts of the evil one. Amen."},
    {"day":27, "title":"The Shield of Faith", "passage":"Ephesians 6:15-17",
     "text":"Above all, taking the shield of faith, wherewith ye shall be able to quench all the fiery darts of the wicked. And take the helmet of salvation, and the sword of the Spirit, which is the word of God.",
     "exposition":"'Above all, taking the shield of faith.' The Roman shield was large enough to cover the whole body, and it was soaked in water before battle to extinguish the flaming arrows of the enemy. So faith covers the whole man and quenches every fiery dart of doubt, fear, temptation, and accusation that Satan hurls against us. The Puritan John Bunyan portrayed this beautifully in 'The Pilgrim's Progress' when Christian passed through the Valley of the Shadow of Death. Every kind of horror assailed him, but he pressed on with his sword drawn and his shield raised, crying out, 'I will walk in the strength of the Lord God.' The helmet of salvation protects the mind -- the assurance of our salvation guards our thoughts from despair and keeps us fighting when everything within us wants to surrender. And the sword of the Spirit, the Word of God, is our only offensive weapon. Every other piece of armor is defensive; this alone enables us to attack. Jesus Himself demonstrated its use in the wilderness when He answered every temptation of Satan with 'It is written.' The believer who knows his Bible, who has hidden God's Word in his heart, who can wield the Scriptures with precision and power, is a terror to the forces of darkness. Amen."},
    {"day":28, "title":"Praying Always with All Prayer", "passage":"Ephesians 6:18-20",
     "text":"Praying always with all prayer and supplication in the Spirit, and watching thereunto with all perseverance and supplication for all saints; and for me, that utterance may be given unto me, that I may open my mouth boldly, to make known the mystery of the gospel.",
     "exposition":"Prayer is the atmosphere in which the whole armor of God functions. Without prayer, the armor is merely a museum exhibit -- impressive to look at but useless in battle. The Puritans were, above all else, men and women of prayer. They prayed in their closets, at their tables, in their churches, and in their marketplaces. They prayed morning, noon, and night. They prayed in prosperity and in persecution. John Bradford, the Puritan martyr, was said to have spent so much time on his knees that they grew callused. Matthew Henry's father, Philip Henry, would pray for hours at a time, weeping over the sins of the nation and the needs of the church. Paul asks for prayer not for his comfort or release from prison, but for boldness in preaching. This reveals the heart of a true minister -- his greatest concern is not his own welfare but the advance of the gospel. As Richard Baxter wrote, 'I preached as a dying man to dying men, as never sure to preach again.' May we all catch that sense of urgency, that holy boldness, that consuming passion for the souls of men and the glory of God. Amen."},
    {"day":29, "title":"Grace Be with All Them That Love Our Lord", "passage":"Ephesians 6:21-24",
     "text":"But that ye also may know my affairs, and how I do, Tychicus, a beloved brother and faithful minister in the Lord, shall make known to you all things. Peace be to the brethren, and love with faith, from God the Father and the Lord Jesus Christ. Grace be with all them that love our Lord Jesus Christ in sincerity. Amen.",
     "exposition":"Paul closes this sublime epistle with a blessing of peace, love, faith, and grace. Four words that summarize the entire Christian life. Peace with God through the blood of the cross. Love poured into our hearts by the Holy Spirit. Faith as the instrument by which we receive every blessing. And grace -- always grace, first and last and everything in between. Notice the final condition: 'Grace be with all them that love our Lord Jesus Christ in sincerity.' The word 'sincerity' literally means 'incorruptibility.' Grace is for those who love Christ with an undying, imperishable, incorruptible love -- a love that endures through trial and temptation, through suffering and sorrow, through persecution and death. As Samuel Rutherford wrote from his prison cell, 'I have tasted Christ's love, and I am cured forever of any desire for what the world can offer.' May this be our testimony as we conclude our study of Ephesians. We have climbed the Alps of divine revelation. We have gazed upon the riches of grace, the mystery of the church, the calling to holiness, and the armor of God. Now let us walk worthy of all that we have received, and may grace -- sovereign, free, eternal, inexhaustible grace -- be with us all. Amen."},
    {"day":30, "title":"The Puritan Vision of the Christian Life", "passage":"Selected Texts",
     "text":"Trust in the Lord with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths. -- Proverbs 3:5-6",
     "exposition":"As we near the end of our July journey, let us pause to reflect on what the Puritans have taught us through their writings and their lives. The Puritan vision of the Christian life was intensely practical, deeply personal, and gloriously God-centered. They believed that every moment of every day was to be lived under the eye of God and for the glory of God. Richard Baxter's 'The Reformed Pastor' challenged ministers to examine their own hearts before presuming to examine others. John Owen's works on the mortification of sin taught that holiness is not passive but active -- a daily war against the flesh, fought with the weapons of Scripture and prayer. Jeremiah Burroughs' 'The Rare Jewel of Christian Contentment' showed that true happiness is found not in circumstances but in Christ. William Bridge's 'A Lifting Up for the Downcast' ministered hope to the despairing. And Thomas Watson's 'All Things for Good' demonstrated from Scripture that God's providence works every event -- even the painful ones -- for the eternal benefit of His children. These men were not ivory tower theologians; they were pastors, soldiers, exiles, and prisoners who lived what they taught. They lost their positions, their freedom, and sometimes their lives for the sake of conscience. And through it all, they held fast to the sovereignty of God, the sufficiency of Christ, and the power of the Spirit. May their example inspire us to live with the same depth, the same seriousness, and the same joy. Amen."},
    {"day":31, "title":"The God of All Grace", "passage":"1 Peter 5:10-11",
     "text":"But the God of all grace, who hath called us unto his eternal glory by Christ Jesus, after that ye have suffered a while, make you perfect, stablish, strengthen, settle you. To him be glory and dominion for ever and ever. Amen.",
     "exposition":"We close this month with Peter's benediction, which gathers up all the themes we have explored in Ephesians and applies them to the suffering, struggling believer. The God of all grace -- not some grace, not occasional grace, but all grace for all needs at all times. He has called us unto His eternal glory -- this is our destination, our inheritance, our certain hope. After that ye have suffered a while -- the suffering is real, but it is temporary. It is 'a while,' not forever. And the four verbs that follow are God's promises to every child of His: He will make you perfect -- complete, mature, lacking nothing. He will establish you -- make you firm, steady, unshakeable. He will strengthen you -- infuse you with divine power for every trial. He will settle you -- plant you on a foundation that cannot be moved. As Thomas Brooks wrote, 'God's people may be bruised reeds, but He will not break them. They may be smoking flax, but He will not quench them. He will fan the spark into a flame and strengthen the reed into an oak.' To Him be glory and dominion forever. This has been our theme all month, and it shall be our song for eternity. The God who began a good work in us will bring it to completion at the day of Jesus Christ. Soli Deo Gloria. Amen."},
]


async def generate_study_episodes():
    import edge_tts

    # Load existing episodes
    with open(EPISODES_FILE) as f:
        episodes = json.load(f)

    # Remove old July study episodes if any
    episodes = [e for e in episodes if not (e.get('section') in ('study', None) and e.get('date','').startswith('2026-07'))]

    new_eps = []
    start_id = 8001

    for ep_data in STUDY_EPISODES:
        day = ep_data["day"]
        ep_id = start_id + day - 1
        date_str = f"2026-07-{day:02d}"
        title = ep_data["title"]

        # Build script
        script = f'PURITAN GOLD -- Daily Study\n"{title}"\nJuly {day}, 2026\n\n---\n\n'
        script += f'"{ep_data["text"]}" -- {ep_data["passage"]}\n\n'
        script += ep_data["exposition"]

        # Save script
        script_path = os.path.join(SCRIPTS_DIR, f"ep_{ep_id}.txt")
        with open(script_path, "w") as f:
            f.write(script)

        # Generate audio
        audio_file = f"audio/ep{ep_id}.mp3"
        audio_path = os.path.join(BASE_DIR, audio_file)

        if os.path.exists(audio_path) and os.path.getsize(audio_path) > 1000:
            print(f"  SKIP day {day} — audio exists")
            size = os.path.getsize(audio_path)
        else:
            print(f"  Day {day}: {title} ({len(script)} chars)...")
            tts_text = f"{title}. {ep_data['passage']}. {ep_data['text']} {ep_data['exposition']}"
            comm = edge_tts.Communicate(tts_text, VOICE, rate=RATE, pitch=PITCH, volume=VOLUME)
            await comm.save(audio_path)
            size = os.path.getsize(audio_path)
            print(f"    DONE: {size/1024:.0f}KB")

        dur_secs = int(size / 16000)
        new_eps.append({
            "id": ep_id,
            "title": title,
            "subtitle": ep_data["passage"],
            "description": ep_data["exposition"][:200] + "...",
            "file": audio_file,
            "duration": f"{dur_secs // 60}:{dur_secs % 60:02d}",
            "durationSecs": dur_secs,
            "fileSize": size,
            "date": date_str,
            "series": "Ephesians",
            "section": "study",
            "tags": ["study", "ephesians", "puritan"],
            "day": day,
        })
        await asyncio.sleep(0.2)

    episodes.extend(new_eps)
    episodes.sort(key=lambda e: e["id"])

    with open(EPISODES_FILE, "w") as f:
        json.dump(episodes, f, indent=2)

    print(f"\n=== Added {len(new_eps)} July study episodes ===")


async def main():
    print("=== Generating July 2026 Study Episodes: Ephesians ===")
    print(f"Voice: {VOICE}, Rate: {RATE}, Pitch: {PITCH}, Volume: {VOLUME}")
    await generate_study_episodes()


if __name__ == "__main__":
    asyncio.run(main())
